### ISSUE TITLE
Frontpage: list records/communities

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/product-rdm#14]
### Goal

Easily display records on the frontpage

### Tasks

- Frontend:
   - Caching of frontpage
- Frontpage
    - Diplay records (via JS app)
    - Display communities (via JS app)
- Backend
    - React-Searchkit/Invenio-Search features to make it easy

**Comment by fenekku** [comment]
Make the frontpage easy to customize for instance administrator by placing it in the cookiecutter, so they just have to modify existing files.

Concrete task:

move the frontpage html/js/less from app-rdm into the cookiecutter project, so that the frontpage. which will always be overwritten, doesn't stay in app-rdm. Otherwise, more configuration needed / webpack still builds its assets (pretty sure) and app-rdm is laden with dead code. I will put that in the product one.
